[package]

name = "geocoding"
description = "Geocoding library for Rust"
version = "0.0.1"
authors = ["Blake Grotewold <hello@grotewold.me>"]
license = "Apache-2.0"
repository = "https://github.com/georust/rust-geocoding"
